<header class="site-header">
    <div class="container-fluid">

        <a href="/" class="site-logo">
            <img class="hidden-md-down" src="/dist/startui/img/logo.png" alt="">
            <img class="hidden-lg-up" src="/dist/startui/img/logo.png" alt="">
        </a>

        <button id="show-hide-sidebar-toggle" class="show-hide-sidebar">
            <span>toggle menu</span>
        </button>

        <button class="hamburger hamburger--htla">
            <span>toggle menu</span>
        </button>
        <div class="site-header-content">
            <div class="site-header-content-in">
                <div class="site-header-shown">
                    <div class="dropdown user-menu">
                        <button class="dropdown-toggle" id="dd-user-menu" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="/dist/startui/img/avatar-2-64.png" alt="">
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dd-user-menu">
                            <div class="dropdown-item" ><span class="font-icon glyphicon glyphicon-user"></span><?php echo $this->identity()->getFirstName() . ' ' . $this->identity()->getLastName();?></div>
                            
                            <?php if($this->login()['userChainCount'] >0) { ?>
                            <a class='dropdown-item' href="<?php echo $this->url('user/logout'); ?>/all"><span class="font-icon glyphicon glyphicon-log-out"></span>Logout all</a>
                            <?php } ?>

                            <a class="dropdown-item" href="<?php echo $this->url('user/logout'); ?>"><span class="font-icon glyphicon glyphicon-log-out"></span>Logout</a>

                            
                        </div>
                    </div>

                    <button type="button" class="burger-right">
                        <i class="font-icon-menu-addl"></i>
                    </button>
                </div><!--.site-header-shown-->

                <div class="mobile-menu-right-overlay"></div>
            </div><!--site-header-content-in-->
        </div><!--.site-header-content-->
    </div><!--.container-fluid-->
</header><!--.site-header-->