<?php
/**
 * @var User\Model\User $user
 */
$this->headTitle('Tutors');
$this->headLink()
    ->prependStylesheet('/dist/startui/css/custom.css')
    ->prependStylesheet('/dist/startui/css/main.css')
    ->prependStylesheet('/dist/startui/css/lib/bootstrap/bootstrap.min.css')
    ->prependStylesheet('/dist/startui/css/lib/font-awesome/font-awesome.min.css')
    ->prependStylesheet('/dist/startui/scripts/dropzone/dropzone.css')
    ->prependStylesheet('/dist/startui/css/separate/vendor/datatables-net.min.css')
    ->prependStylesheet('/dist/startui/css/lib/datatables-net/datatables.min.css');
$this->inlineScript()
    ->prependFile('/dist/startui/scripts/validator/magic.js')
    ->prependFile('/dist/startui/js/app.js')
    ->prependFile('/dist/startui/js/lib/datatables-net/datatables.min.js')
    ->prependFile('/dist/startui/js/plugins.js')
    ->prependFile('/dist/startui/js/lib/bootstrap/bootstrap.min.js')
    ->prependFile('/dist/startui/js/lib/tether/tether.min.js')
    ->prependFile('/dist/startui/js/lib/jquery/jquery.min.js');
?>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
    (function ($) {
        $('#user-table').DataTable({'aaSorting': []});
    })(jQuery);
JS;
$this->inlineScript()->captureEnd();
?>
<div class="page-content <?php if($this->login()['userChainCount'] >0 ) { echo "padding-zero"; } ?>">
    <div class="container-fluid">
        <?php if (\Rbac\Role\Administrator::class === $this->identity()->getRole()) { ?>
            <a href="<?php echo $this->url('tutor/form/tutor'); ?>" class="btn btn-inline btn-secondary">Add Tutor</a><br><br>
        <?php } ?>


         <?php 
            if (\Rbac\Role\Administrator::class === $this->identity()->getRole()) { ?>
                <p>
                    <form action="<?php echo $this->url(); ?>" method="GET">
                        <select name="course" class="form-control" onchange="this.form.submit()">
                            <option value=""></option>
                            <?php foreach ($this->courseResultSet as $course) { ?>
                                

                                <option value="<?php echo $course->getId(); ?>" <?php
                                echo $course->getId() === $this->selectedCourse ? 'selected' : ''; ?>>
                                    <?php
                                    echo $course->getName();
                                    ?>
                                </option>
                            <?php } ?>
                        </select>
                    </form>
                </p>
            <?php } ?>



        <!--<form action="<?php echo $this->url('tutor/user/view/resultset'); ?>" method="get">
        <input value="<?php echo $this->search['identity'] ?? ''; ?>" type="text" name="search[identity]" placeholder="Search Tutor" class="form-control search-tutor" onblur="this.form.submit()">-->
        <br>
        <?php 
        if (count($this->resultSet) > 0) { ?>
            <table id="user-table" class="display table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Overdue</th>
                <th>Unmarked</th>
                <th>Avg Marking Time</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
                <?php

                 foreach ($this->resultSet as $user) { ?>
                    <tr>
                        <td><?php echo $user->getFirstName(); ?></td>
                        <td><?php echo $user->getLastName(); ?></td>
                        <td><?php echo $user->getUsername(); ?></td>
                        <td><?php echo $user->getIdentity(); ?></td>
                        <td><?php echo $user->getPhone(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('assignment/view/work/resultset', ['filter' => 'overdue']); ?>?tutor=<?php echo $user->getId(); ?>">
                                <?php echo $this->assignmentWork()->countOverdueByTutor($user->getId()); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('assignment/view/work/resultset', ['filter' => 'due']); ?>?tutor=<?php echo $user->getId(); ?>">
                                <?php echo $this->assignmentWork()->countUnmarkedByTutor($user->getId()); ?>
                            </a>
                        </td>
                        <td><?php if ($user->getMarkingCount() > 0) { echo round($user->getMarkingTime() / $user->getMarkingCount()) . ' days'; }; ?></td>
                        <td>
                            <a class="btn btn-inline btn-secondary" href="<?php echo $this->url('tutor/form/tutor', ['id' => $user->getId()]); ?>">Edit</a>
                            <form method='GET' class='inline-block' action='<?php echo $this->url('user/form/loginas', ['userId' => $user->getId()]); ?>'>
                            <button type="submit" class="btn btn-inline btn-secondary">Login as this user</button>
                        </form>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
        <?php } ?>
        <!--</form>-->
    </div>
</div>