<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <?php echo $this->headTitle('LMS')->setSeparator(' - ')->setAutoEscape(false) ?>

    <link href="/dist/startui/img/favicon.144x144.png" rel="apple-touch-icon" type="image/png" sizes="144x144">
    <link href="/dist/startui/img/favicon.114x114.png" rel="apple-touch-icon" type="image/png" sizes="114x114">
    <link href="/dist/startui/img/favicon.72x72.png" rel="apple-touch-icon" type="image/png" sizes="72x72">
    <link href="/dist/startui/img/favicon.57x57.png" rel="apple-touch-icon" type="image/png">
    <link href="/dist/startui/img/favicon.png" rel="icon" type="image/png">
    <link href="/dist/startui/img/favicon.ico" rel="shortcut icon">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
</head>
<?php
    $bodyClass = '';
    if (null != $this->placeholder('bodyClass')->getValue()) {
        $bodyClass = 'with-side-menu-addl-full';
    } elseif ($this->identity()) {
        $bodyClass = 'with-side-menu';
    }
?>
<body class="<?php echo $bodyClass; ?>">

<?php if ($this->identity()) { ?>
    <?php echo $this->render('layout::default/header'); ?>
    <?php echo $this->render('layout::default/navigation'); ?>
    <?php echo $this->render('layout::default/breadcrumb'); ?>
    
    <?php echo $this->content ?>
<?php } else { ?>
    <?php echo $this->content ?>
<?php } ?>

<?php echo $this->inlineScript(); ?>

</body>
</html>
