<?php
$this->headTitle('Course');
$this->headLink()
    ->prependStylesheet('/dist/startui/css/custom.css')
    ->prependStylesheet('/dist/startui/css/main.css')
    ->prependStylesheet('/dist/startui/css/lib/bootstrap/bootstrap.min.css')
    ->prependStylesheet('/dist/startui/css/lib/font-awesome/font-awesome.min.css');
$this->inlineScript()
    ->prependFile('/dist/startui/scripts/validator/magic.js')
    ->prependFile('/dist/startui/scripts/tinymce/js/tinymce/tinymce.min.js')
    ->prependFile('/dist/startui/js/app.js')
    ->prependFile('/dist/startui/js/plugins.js')
    ->prependFile('/dist/startui/js/lib/bootstrap/bootstrap.min.js')
    ->prependFile('/dist/startui/js/lib/tether/tether.min.js')
    ->prependFile('/dist/startui/js/lib/jquery/jquery.min.js');
?>
<div class="page-content <?php if($this->login()['userChainCount'] >0 ) { echo "padding-zero"; } ?>">
    <div class="container-fluid">
        <?php
        /**
         * @var \Course\Form\Course $form
         */
        $form = $this->form;

        /**
         * @var \Zend\Form\Element $submitElement
         */
        $submitElement = $form->get('submit');
        $submitElement->setAttribute('class', 'btn-inline btn-secondary');

        $form->setAttribute('action', $this->url('course/post/course'));

        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('id'));
        echo $this->twbsFormRow($form->get('name'));
        echo $this->twbsFormRow($form->get('summary'));
        echo $this->twbsFormRow($form->get('tiny-image'));
        echo $this->twbsFormRow($submitElement);
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
    (function ( $ ) {
        tinymce.init({ 
            selector: 'textarea[name="summary"]',
            height: 400,
            plugins: [
                "advlist autolink lists link image charmap print preview hr searchreplace wordcount code fullscreen table contextmenu paste textcolor colorpicker"
            ],
            toolbar1: "undo redo styleselect bold italic forecolor backcolor alignleft aligncenter alignright alignjustify bullist numlist outdent indent link image print preview code",
            images_upload_url: '/uploader/upload',
            file_picker_callback: function(callback, value, meta) {
              if (meta.filetype == 'image') {
                $('#tiny-image').trigger('click');
                $('#tiny-image').on('change', function() {
                  var file = this.files[0];
                  var reader = new FileReader();
                  reader.onload = function(e) {
                    callback(e.target.result, {
                      alt: ''
                    });
                  };
                  reader.readAsDataURL(file);
                });
              }
            },
            setup: function (editor) {
                editor.on('change', function () {
                    editor.save();
                });
            }
        });
    })(jQuery);
JS;
$this->inlineScript()->captureEnd();
