<?php
$this->headLink()
    ->prependStylesheet('/dist/startui/css/custom.css')
    ->prependStylesheet('/dist/startui/css/main.css')
    ->prependStylesheet('/dist/startui/css/lib/bootstrap/bootstrap.min.css')
    ->prependStylesheet('/dist/startui/css/lib/font-awesome/font-awesome.min.css')
    ->prependStylesheet('/dist/startui/scripts/dropzone/dropzone.css');
$this->inlineScript()
    ->prependFile('/dist/startui/scripts/validator/magic.js')
    ->prependFile('/dist/startui/scripts/dropzone/dropzone.js')
    ->prependFile('/dist/startui/scripts/tinymce/js/tinymce/tinymce.min.js')
    ->prependFile('/dist/startui/js/app.js')
    ->prependFile('/dist/startui/js/plugins.js')
    ->prependFile('/dist/startui/js/lib/bootstrap/bootstrap.min.js')
    ->prependFile('/dist/startui/js/lib/tether/tether.min.js')
    ->prependFile('/dist/startui/js/lib/jquery/jquery.min.js');
?>
<div class="page-content <?php if($this->login()['userChainCount'] >0 ) { echo "padding-zero"; } ?>">
    <div class="container-fluid">
		<section class="card">
			<header class="card-header card-header-lg">
				Payment Details
			</header>
				<div class="card-block invoice">
					<div class="row">
						<div class="col-lg-6 company-info">

						</div>
						<div class="col-lg-6 clearfix invoice-info">

						</div>
					</div>
					<div class="row table-details">
						<div class="col-lg-12">
							<table class="table table-bordered">
								<thead>
									<tr>
										<th>Description</th>
										<th class="text-center">Quantity</th>
										<th class="text-center">Unit Cost</th>
										<th class="text-center">Total</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Hard Copy Certificate<br/>										
										Course Name : <?php echo $this->courseName;?><br/><br/>
											<?php 
											$data = $this->address;
											if ($this->coupon) {
												$coupon = $this->coupon;
											} else {
												$coupon = 'z';
											}

											$linkURL = $this->url('certificate/form/address',array('examid' => $this->examId,'coupon' => $coupon,'id' => $this->addressId));

											if($data) {
											//var_dump($data);

											?>
											<strong>Send to address: </strong><br/>
											<?php echo $data->address;?><br/>

											<?php if ($data->address2) {?>
												<?php echo $data->address2;?><br/>
											<?php } ?>

											<?php echo $data->city;?><br/>
											<?php 
											$states = $this->states;
											$countries = $this->countries;
											//var_dump ($states);
											echo $states[$data->state_id].', '.$countries[$data->country_id].' '.$data->postal_code;?><br/><br/>
											Are you sure to send this address ? (<a href="<?php echo $linkURL; ?>">or you can edit here</a>)

											<?php } else {
												echo "You have not add adress. Please <a href='$linkURL'>add here</a>.";
											} ?>
										</td>
										<td class="text-center">1</td>
										<td class="text-center">&#163;25</td>
										<td class="text-center">&#163;25</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-7 terms-and-conditions">
							<br/>


						</div>
						<div class="col-lg-5 clearfix">
							<br/>
							<div class="total-amount text-right">
								<div>Sub - Total amount: <b>&#163;25.00</b></div>
								<?php if (!$this->discount) {?>
								<div>Discount: &#163;0</div>
								<div>Grand Total: <span class="colored">&#163;25.00</span><br/><br/></div>
								<?php 
								$price = '2500';
								} else { ?>
								<div>Discount: &#163;-15</div>
								<div>Grand Total: <span class="colored">&#163;15.00</span><br/><br/></div>
								<?php 
								$price = '1500';
								} ?>
								<div class="actions">
									<?php
									/**
									 * @var \Zend\Form\Form $form
									 */
									$form = $this->form;

									$stripe = array(
									  "secret_key"      => $this->stripe_secret_key,
									  "publishable_key" => $this->stripe_publishable_key
									);

									\Stripe\Stripe::setApiKey($stripe['secret_key']);

									?>

									<?php
									/**
									 * @var \Zend\Form\Element $submitElement
									 */
									$submitElement = $form->get('submit');
									$submitElement->setAttribute('class', 'btn-inline btn-secondary');

									$form->setAttribute('action', $this->url('certificate/post/payment'));

									echo $this->form()->openTag($form);

									$this->headTitle('Payment');
									?>
									<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
											  data-key="<?php echo $stripe['publishable_key']; ?>"
											  data-description="Course : <?php echo $this->courseName;?>"
											  data-amount="<?php echo $price;?>"
											  data-currency="GBP"
											  data-locale="auto"></script>
									<?php
									echo $this->formRow($form->get('coupon'));
									echo $this->formRow($form->get('exam_id'));
									echo $this->formRow($form->get('student_id'));
									echo $this->formRow($form->get('address_id'));
									echo $this->formRow($form->get('amount'));

									//echo $this->twbsFormRow($submitElement);
									echo $this->form()->closeTag();
									?>
									<!--<button class="btn btn-rounded btn-inline">Send</button>
									<button class="btn btn-inline btn-secondary btn-rounded">Print</button>-->
								</div>
							</div>
						</div>
					</div>
				</div>
		</section>
    </div>
</div>