<?php
$this->headTitle('Please Select');
$this->headLink()
    ->prependStylesheet('/dist/startui/css/custom.css')
    ->prependStylesheet('/dist/startui/css/main.css')
    ->prependStylesheet('/dist/startui/css/lib/bootstrap/bootstrap.min.css')
    ->prependStylesheet('/dist/startui/css/lib/font-awesome/font-awesome.min.css')
    ->prependStylesheet('/dist/startui/scripts/dropzone/dropzone.css');
$this->inlineScript()
    ->prependFile('/dist/startui/scripts/validator/magic.js')
    ->prependFile('/dist/startui/scripts/dropzone/dropzone.js')
    ->prependFile('/dist/startui/scripts/tinymce/js/tinymce/tinymce.min.js')
    ->prependFile('/dist/startui/js/app.js')
    ->prependFile('/dist/startui/js/plugins.js')
    ->prependFile('/dist/startui/js/lib/bootstrap/bootstrap.min.js')
    ->prependFile('/dist/startui/js/lib/tether/tether.min.js')
    ->prependFile('/dist/startui/js/lib/jquery/jquery.min.js');
?>
<div class="page-content <?php if($this->login()['userChainCount'] >0 ) { echo "padding-zero"; } ?>">
    <div class="container-fluid">
		<section class="card">
		<div class="card-block">
			<div class="row">
				<div class="col-lg-12">
				<p>Please select Exam from below list</p>
				<?php
				/**
				 * @var \Zend\Form\Form $form
				 */
				$result = $this->examIds;
				$examTable = $this->examTable;
				$courseUser = $this->courseUser;
				$examIdsbyCourseId = $this->examIdsbyCourseId;

				foreach ($courseUser as $course) {
					
					$courseName = $course->getName();
					$examIds = $examIdsbyCourseId[$course->getId()];
					if (count($examIds) > 0) {
						echo '<section class="card mb-3"><header class="card-header card-header-xl">'.$courseName.'</header><div class="card-block"><p class="card-text">';

						foreach($examIds as $examId) {
							$MyExam = $examTable->fetchById($examId)->current();
							$examName = $MyExam->getName();
							echo '<a href="'.$this->url('certificate/form/payment',['id' => $examId, 'coupon' => $this->coupon]).'" class="btn btn-primary">'.$examName.'</a>&nbsp;';
						}
					
						echo '</p></div></section>';

					}

				}
				//var_dump($examIdsbyCourseId);
				?>
				</div>
			</div>
		</div>
		</section>
    </div>
</div>
